#!/usr/bin/with-contenv bash

ALGORITHM=${ALGORITHM:-"cryptonight"}
HOST=${HOST:-"xmr.pool.minergate.com:45700"}
THREADS=${THREADS:-"4"}
USER=${USER:-"truefractal@gmail.com"}
PASS=${PASS:-"x"}

exec /cpuminer-multi/minerd -a $ALGORITHM -o stratum+tcp://$HOST -u $USER -p $PASS --threads $THREADS
