version: '2'

services:
  
  cpuminer-app:
    image: tiredofit/miner
    container_name: cpuminer-app
    environment:
      - ZABBIX_HOSTNAME=cpuminer-app

      - ALGORITHM=cryptonight
      - HOST=xmr.pool.minergate.com:45700
      - THREADS=4
      - USER=@gmail.com
      - PASS=x
    restart: always

